Repository unform/unform, pull requests merged in 2019-05, with the labels that each got.

#18 Skip Travis builds in documentation changes
  .travis.yml
Labels: enhancement

#15 Add contributing guidelines
  .github/CONTRIBUTING.md
Labels: docs, meta

#19 Update TOC and `Contributing` section in README
  README.md
Labels: docs, meta

#21 Update README's first look and adds some details about our guidelines
  README.md
Labels: docs, meta

#25 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: docs

#14 Fix initial set value in select
  lib/components/Select.tsx
Labels: bug

#28 Remove skip rule from Travis
  .travis.yml
Labels: bug

#34 feat: Add commitlint to lint commit messages
  .github/CONTRIBUTING.md
  .travis.yml
  commitlint.config.js
  package.json
  yarn.lock
Labels: ci, docs, enhancement, meta

#39 docs: Fix badges link [skip ci]
  README.md
Labels: docs

#50 chore: Update issue templates to improve consistency
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation-report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
Labels: meta

#45 feat: Add pull request template
  .github/PULL_REQUEST_TEMPLATE
Labels: meta

#63 docs: Add section about skipping building process
  .github/CONTRIBUTING.md
Labels: docs, meta

#64 docs: Add description to the Initial Data section
  README.md
Labels: docs

#72 docs: Fix readme "style"
  README.md
Labels: docs

#75 chore: Restore textarea component
  __tests__/components/Textarea.spec.tsx
  lib/components/Input.tsx
  lib/components/Textarea.tsx
  lib/index.ts
Labels: enhancement

#85 docs: Fix typo in ToC
  .github/CONTRIBUTING.md
Labels: docs, meta

#84 chore: Run lint-staged on tests and example
  .prettierrc
  lib/Form.tsx
  package.json
Labels: enhancement
