Repository unform/unform, pull requests merged in 2019-06, with the labels that each got.

#89 chore: Commit files after lint-staged changes
  package.json
Labels: meta

#92 docs: Additional documentation on how the schema works
  README.md
Labels: docs

#80 docs: Add a docusaurus project
  .DS_Store
  docs/.dockerignore
  docs/.gitignore
  docs/Dockerfile
  docs/crowdin.yaml
  docs/docker-compose.yml
  docs/docs/contributing/contributing.md
  docs/docs/custom_elements/custom_elements.md
  docs/docs/custom_elements/react_datepicker.md
  docs/docs/custom_elements/react_select.md
  docs/docs/guides/basics.md
  docs/docs/guides/elements.md
  docs/docs/guides/initial_data.md
  docs/docs/guides/installation.md
  docs/docs/guides/manipulate_data.md
  docs/docs/guides/nested_fields.md
  docs/docs/guides/reset_form.md
  docs/docs/guides/styling.md
  docs/docs/guides/validation.md
  docs/website/README.md
  docs/website/blog/2019-05-26-blog-post.md
  docs/website/core/Footer.js
  docs/website/i18n/en.json
  docs/website/languages.js
  docs/website/package.json
  docs/website/pages/en/community.js
  docs/website/pages/en/help-with-translations.js
  docs/website/pages/en/help.js
  docs/website/pages/en/index.js
  docs/website/pages/en/users.js
  docs/website/sidebars.json
  docs/website/siteConfig.js
  docs/website/static/css/custom.css
  docs/website/static/css/styles.css
  docs/website/static/img/community.svg
  docs/website/static/img/favicon.ico
  docs/website/static/img/logo.png
  docs/website/static/img/oss_logo.png
  docs/website/static/img/undraw_code_review.svg
  docs/website/static/img/undraw_monitor.svg
  docs/website/static/img/undraw_note_list.svg
  docs/website/static/img/undraw_online.svg
  docs/website/static/img/undraw_open_source.svg
  docs/website/static/img/undraw_operating_system.svg
  docs/website/static/img/undraw_react.svg
  docs/website/static/img/undraw_tweetstorm.svg
  docs/website/static/img/undraw_youtube_tutorial.svg
Labels: docs

#96 docs: Update some instructions and minimal changes
  docs/website/i18n/en.json
  docs/website/i18n/pt-BR.json
  docs/website/pages/en/index.js
  docs/website/pages/pt-BR/index.js
  docs/website/sidebars.json
  docs/website/siteConfig.js
  docs/website/static/img/community.svg
  docs/website/static/img/favicon.ico
  docs/website/static/img/favicon.png
  docs/website/translated_docs/pt-BR/basics.md
  docs/website/translated_docs/pt-BR/contributing.md
  docs/website/translated_docs/pt-BR/elements.md
  docs/website/translated_docs/pt-BR/initial-data.md
  docs/website/translated_docs/pt-BR/installation.md
  docs/website/translated_docs/pt-BR/manipulate-data.md
  docs/website/translated_docs/pt-BR/nested-fields.md
  docs/website/translated_docs/pt-BR/reset-form.md
  docs/website/translated_docs/pt-BR/usefield.md
  docs/website/translated_docs/pt-BR/validation.md
Labels: docs

#99 Docs/assets fix
  docs/website/siteConfig.js
Labels: ci, docs

#100 docs: Add slash on baseUrl
  docs/website/siteConfig.js
Labels: ci, docs

#46 chore: Make select placeholder optional
  __tests__/Form.spec.tsx
  __tests__/components/Select.spec.tsx
  example/src/App.tsx
  lib/components/Select.tsx
Labels: enhancement

#77 feat: Allow to use html form attributes
  .prettierrc
  __tests__/Form.spec.tsx
  lib/Form.tsx
  lib/types.ts
Labels: enhancement

#107 fix: Consider context inside unregisterField
  lib/Form.tsx
Labels: bug
